# netlify.toml (repo root)

[build]
  publish = "public"   # <-- tell Netlify to serve the /public folder (where index.html lives)
  functions = "netlify/functions"  # <-- tell Netlify where to find functions

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# TEMPORARY SOLUTION: Using Netlify functions until backend is deployed
# This provides basic functionality to test the UI while backend deployment is in progress

# Audio upload endpoints - MUST come before catch-all
[[redirects]]
  from = "/api/asr/en"
  to = "/.netlify/functions/asr-upload"
  status = 200
  force = true

[[redirects]]
  from = "/api/asr/ht" 
  to = "/.netlify/functions/asr-upload"
  status = 200
  force = true

# Sample linking endpoint
[[redirects]]
  from = "/api/samples/link"
  to = "/.netlify/functions/samples-link"
  status = 200
  force = true

# Health check endpoint
[[redirects]]
  from = "/healthz"
  to = "/.netlify/functions/healthz"
  status = 200
  force = true

# Simple test endpoint
[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test-simple"
  status = 200
  force = true

# Future: Replace with real backend deployment
# [[redirects]]
#   from = "/api/*"
#   to = "https://YOUR-BACKEND-URL.com/api/:splat"
#   status = 200
#   force = true

# Handle client-side routing (but NOT API calls or functions)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = ["!/api/*", "!/.netlify/*"]}