services:
  - type: web
    name: translator-voice-en-ht-backend
    env: node
    plan: free
    buildCommand: echo "No build needed"
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000